[package]
name = "utoipauto"
authors = ["ProbablyClem", "RxDiscovery"]
version = "0.1.1"
edition = "2021"
keywords = ["utoipa", "openapi", "swagger", "path", "auto"]
description = "Rust Macros to automate the addition of Paths/Schemas to Utoipa crate, simulating Reflection during the compilation phase"
categories = [
    "parsing",
    "development-tools::procedural-macro-helpers",
    "web-programming",
]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/ProbablyClem/utoipauto"
homepage = "https://github.com/ProbablyClem/utoipauto"
[lib]


[dependencies]
utoipauto-macro = { path = "./utoipauto-macro" }


[dev-dependencies]
utoipa = { version = "4.1.0", features = ["preserve_path_order"] }
syn = { version = "2.0.39", features = ["extra-traits", "full"] }
